### ISSUE TITLE
test_runner.py --unit crash

### ISSUE THREAD

**Issue by frulo** [SpatialMetabolomics/SM_distributed#7]
Hello,
I tried to install the engine...

But the test produce the following crash [crash.txt](https://github.com/SpatialMetabolomics/SM_distributed/files/295597/crash.txt)

kind regards

Orlando

**Comment by lomereiter** [comment]
Please try to upgrade the package to the latest version:
```
pip install --upgrade cpyImagingMSpec
```

**Comment by frulo** [comment]
after the upgrade I got the following crash
[crash.txt](https://github.com/SpatialMetabolomics/SM_distributed/files/297071/crash.txt)

**Comment by lomereiter** [comment]
Please upgrade `cpyMSpec` in the same way, its latest versions include some performance improvements as well.

**Comment by frulo** [comment]
Now it works, thanks!
