### ISSUE TITLE
Installation Manual

### ISSUE THREAD

**Issue by frulo** [SpatialMetabolomics/SM_distributed#8]
Hello,

very nice description how to install the engine. But not all dependencies was installed.
* missing Linux packages: libfreetype6-dev, libpng-dev, libxml2-dev, libxslt-dev
* missing python packages: boto3, pandas, requests

It would be very helpfull to have some example data (.imzML, .ibd, and config.json) to be able to test the "Molecule Annotation Job".

kind regards,

Orlando

**Comment by lomereiter** [comment]
Hello,

Thanks for trying out our engine.
The installation instructions in the README may be slightly outdated, we will likely direct users to install the engine using the new [Ansible setup scripts](https://github.com/SpatialMetabolomics/sm-engine-ansible).

An example dataset you can find in `tests/data/sci_test_search_job_spheroid_dataset`.

**Comment by frulo** [comment]
Thanks! I will try the ansible setup script
